import { useEffect, useState } from 'react';
import { useUser } from '@clerk/react';
import { Link } from 'wouter';

type Order = { orderId: string; customerName: string; email: string; phone: string; total: string; status: string; statusMessage?: string | null; createdAt: string };
const statuses = ['pending', 'confirmed', 'processing', 'out_for_delivery', 'delivered', 'cancelled'];
export default function AdminOrders() {
  const { user } = useUser(); const email = user?.primaryEmailAddress?.emailAddress || ''; const [orders, setOrders] = useState<Order[]>([]); const [message, setMessage] = useState('');
  const load = () => email && fetch(`/api/orders/admin?adminEmail=${encodeURIComponent(email)}`, { credentials: 'include' }).then((r) => r.ok ? r.json() : []).then(setOrders);
  useEffect(() => { void load(); }, [email]);
  const update = async (orderId: string, status: string) => { await fetch(`/api/orders/${orderId}/status`, { method: 'PATCH', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status, adminEmail: email, statusMessage: status === 'confirmed' ? 'Payment confirmed. Your order is now being prepared.' : undefined }) }); setMessage(`Order ${orderId} updated`); load(); };
  return <div className="min-h-screen bg-background"><header className="fixed inset-x-0 top-0 z-40 border-b border-border/70 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex h-[74px] max-w-[1440px] items-center justify-between px-5 lg:px-10"><Link href="/" className="font-display text-lg tracking-[.15em]">NOBLE LUXE</Link><span className="font-mono-brand text-[10px] uppercase tracking-[.18em] text-primary">Order desk</span></div></header><main className="mx-auto max-w-[1200px] px-5 pb-24 pt-36 lg:px-10"><p className="font-mono-brand text-[10px] uppercase tracking-[.2em] text-primary">Private operations</p><h1 className="mt-3 font-display text-6xl">Order desk.</h1>{message && <p className="mt-5 text-sm text-primary">{message}</p>}<div className="mt-12 space-y-4">{orders.length ? orders.map((order) => <article key={order.orderId} className="border border-border bg-card p-6"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="font-mono-brand text-[10px] uppercase tracking-[.18em] text-primary">{order.orderId}</p><h2 className="mt-2 font-display text-2xl">{order.customerName}</h2><p className="mt-2 text-sm text-muted-foreground">{order.email} · {order.phone}</p></div><p className="font-mono-brand text-lg text-primary">₦{Number(order.total).toLocaleString()}</p></div><div className="mt-6 flex flex-wrap items-center gap-3"><select value={order.status} onChange={(e) => update(order.orderId, e.target.value)} className="border border-border bg-background px-4 py-3 font-mono-brand text-[10px] uppercase tracking-[.12em] text-foreground">{statuses.map((status) => <option key={status} value={status}>{status.replaceAll('_', ' ')}</option>)}</select><span className="text-sm text-muted-foreground">{order.statusMessage || 'Awaiting review'}</span></div></article>) : <div className="border border-dashed border-border p-12 text-center text-sm text-muted-foreground">No orders found, or this account is not the configured admin.</div>}</div></main></div>;
}