import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { Link, useLocation } from 'wouter';
import { ArrowLeft, ArrowRight, Check, FileImage, LockKeyhole, Minus, Plus, ShieldCheck, Upload, X } from 'lucide-react';
import { useCreateOrder } from '@workspace/api-client-react';
import type { OrderInput } from '@workspace/api-client-react';
import type { CartItem } from '@/lib/catalog';
import { formatCurrency, productImage } from '@/lib/catalog';

type CheckoutProps = { cart: CartItem[]; onUpdate: (id: string, size: string, delta: number) => void; onRemove: (id: string, size: string) => void };
type FormState = { customerName: string; phone: string; email: string; address: string; paymentMethod: 'OPay' | 'PalmPay' };

const initialForm: FormState = { customerName: '', phone: '', email: '', address: '', paymentMethod: 'OPay' };

export default function Checkout({ cart, onUpdate, onRemove }: CheckoutProps) {
  const [, setLocation] = useLocation();
  const [form, setForm] = useState(initialForm);
  const [screenshot, setScreenshot] = useState('');
  const [fileName, setFileName] = useState('');
  const [fileError, setFileError] = useState('');
  const fileRef = useRef<HTMLInputElement>(null);
  const createOrder = useCreateOrder();
  const total = useMemo(() => cart.reduce((sum, item) => sum + item.price * item.quantity, 0), [cart]);
  const detailsReady = form.customerName.trim().length >= 2 && form.phone.trim().length >= 7 && form.email.includes('@') && form.address.trim().length >= 8;

  useEffect(() => { if (!cart.length) setLocation('/'); }, [cart.length, setLocation]);

  const setField = (field: keyof FormState, value: string) => setForm((current) => ({ ...current, [field]: value }));
  const handleFile = (file?: File) => {
    if (!file) return;
    if (!file.type.startsWith('image/')) { setFileError('Please choose an image file.'); return; }
    if (file.size > 8 * 1024 * 1024) { setFileError('Please keep the image under 8MB.'); return; }
    setFileError('');
    setFileName(file.name);
    const reader = new FileReader();
    reader.onload = () => setScreenshot(String(reader.result || ''));
    reader.readAsDataURL(file);
  };
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!detailsReady || !screenshot || !cart.length || createOrder.isPending) return;
    const payload: OrderInput = { ...form, address: form.address.trim(), customerName: form.customerName.trim(), email: form.email.trim(), phone: form.phone.trim(), items: cart.map((item) => ({ productId: item.id, productName: item.name, size: item.selectedSize, quantity: item.quantity, price: item.price })), total, paymentScreenshot: screenshot };
    createOrder.mutate({ data: payload }, { onSuccess: (confirmation) => { sessionStorage.setItem(`noble-luxe-order-${confirmation.orderId}`, JSON.stringify(confirmation)); setLocation(`/confirmation/${confirmation.orderId}`); } });
  };

  return (
    <div className="noble-noise min-h-[100dvh]">
      <header className="border-b border-border"><div className="mx-auto flex h-[74px] max-w-[1440px] items-center justify-between px-5 lg:px-10"><Link href="/" className="inline-flex items-center gap-3 text-[10px] uppercase tracking-[0.18em] text-muted-foreground transition hover:text-primary" data-testid="link-back-store"><ArrowLeft className="h-4 w-4" /> Return to showroom</Link><Link href="/" className="font-display text-lg tracking-[0.15em]" data-testid="link-checkout-brand">NOBLE LUXE</Link><span className="flex items-center gap-2 font-mono-brand text-[9px] uppercase tracking-widest text-primary"><LockKeyhole className="h-3.5 w-3.5" /> Secure order</span></div></header>
      {!cart.length ? <div className="mx-auto max-w-lg px-5 py-32 text-center"><p className="font-display text-3xl">Your bag is empty.</p><Link href="/" className="mt-6 inline-flex bg-primary px-5 py-3 text-[10px] uppercase tracking-widest text-primary-foreground" data-testid="link-return-shopping">Return to the edit</Link></div> : <main className="mx-auto max-w-[1440px] px-5 py-12 lg:px-10 lg:py-20"><div className="mb-12"><p className="font-mono-brand text-[10px] uppercase tracking-[0.22em] text-primary">The final detail</p><h1 className="mt-3 font-display text-5xl tracking-[-.04em] lg:text-7xl">Make it yours.</h1></div><div className="grid gap-14 lg:grid-cols-[1fr_.72fr] lg:gap-24"><form onSubmit={submit} className="space-y-12">
        <section><div className="mb-6 flex items-center gap-4"><span className="font-mono-brand text-xs text-primary">01</span><h2 className="font-display text-2xl">Where should we send it?</h2></div><div className="grid gap-5 sm:grid-cols-2"><label className="sm:col-span-2"><span className="field-label">Full name</span><input required value={form.customerName} onChange={(event) => setField('customerName', event.target.value)} className="field" placeholder="Your name" data-testid="input-customer-name" /></label><label><span className="field-label">Phone</span><input required value={form.phone} onChange={(event) => setField('phone', event.target.value)} className="field" placeholder="+234" data-testid="input-customer-phone" /></label><label><span className="field-label">Email</span><input required type="email" value={form.email} onChange={(event) => setField('email', event.target.value)} className="field" placeholder="you@example.com" data-testid="input-customer-email" /></label><label className="sm:col-span-2"><span className="field-label">Delivery address</span><textarea required value={form.address} onChange={(event) => setField('address', event.target.value)} className="field min-h-28 resize-y" placeholder="Street, area, city" data-testid="input-customer-address" /></label></div></section>
        <section><div className="mb-6 flex items-center gap-4"><span className="font-mono-brand text-xs text-primary">02</span><h2 className="font-display text-2xl">Choose your transfer</h2></div><div className="grid gap-3 sm:grid-cols-2">{(['OPay', 'PalmPay'] as const).map((method) => <button type="button" key={method} onClick={() => setField('paymentMethod', method)} className={`border p-5 text-left transition ${form.paymentMethod === method ? 'border-primary bg-primary/10' : 'border-border hover:border-primary/60'}`} data-testid={`button-payment-${method.toLowerCase()}`}><span className="flex items-center justify-between"><span className="font-display text-xl">{method}</span><span className={`flex h-5 w-5 items-center justify-center rounded-full border ${form.paymentMethod === method ? 'border-primary bg-primary text-primary-foreground' : 'border-muted-foreground'}`}>{form.paymentMethod === method && <Check className="h-3 w-3" />}</span><span className="mt-4 block font-mono-brand text-[9px] leading-relaxed text-muted-foreground">
{method === 'OPay'
? 'NOJEEB OLAMILEKAN IBRAHIM · 702 698 7674'
: 'NOJEEB OLAMILEKAN IBRAHIM · 702 698 7674'}
</span></button>)}</div>
        <section><div className="mb-6 flex items-center gap-4"><span className="font-mono-brand text-xs text-primary">03</span><h2 className="font-display text-2xl">Show us the receipt</h2></div><p className="mb-4 max-w-md text-sm leading-relaxed text-muted-foreground">Upload a screenshot of your completed transfer. Your order stays private until we can verify payment.</p>{screenshot ? <div className="relative max-w-sm overflow-hidden border border-primary/50"><img src={screenshot} alt="Payment screenshot preview" className="max-h-72 w-full object-contain bg-secondary" data-testid="img-payment-preview" /><div className="flex items-center justify-between border-t border-primary/30 px-3 py-2"><span className="flex min-w-0 items-center gap-2 truncate font-mono-brand text-[9px] text-muted-foreground"><FileImage className="h-3.5 w-3.5 shrink-0 text-primary" />{fileName}</span><div className="flex items-center gap-3"><button type="button" onClick={() => fileRef.current?.click()} className="text-[9px] uppercase tracking-widest text-primary hover:text-accent" data-testid="button-replace-screenshot">Replace</button><button type="button" onClick={() => { setScreenshot(''); setFileName(''); }} className="text-muted-foreground hover:text-primary" aria-label="Remove payment screenshot" data-testid="button-remove-screenshot"><X className="h-4 w-4" /></button></div></div></div> : <button type="button" onClick={() => fileRef.current?.click()} className="flex min-h-44 w-full max-w-sm flex-col items-center justify-center border border-dashed border-border px-6 text-center transition hover:border-primary hover:bg-primary/5" data-testid="button-upload-screenshot"><Upload className="mb-4 h-6 w-6 text-primary" strokeWidth={1.3} /><span className="text-[10px] font-bold uppercase tracking-[0.17em]">Upload transfer screenshot</span><span className="mt-2 font-mono-brand text-[9px] text-muted-foreground">PNG, JPG up to 8MB</span></button>}<input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={(event) => handleFile(event.target.files?.[0])} data-testid="input-payment-screenshot" />{fileError && <p className="mt-3 text-xs text-destructive" data-testid="status-file-error">{fileError}</p>}</section>
        {createOrder.isError && <div className="border border-destructive/50 bg-destructive/5 p-4 text-sm text-destructive" data-testid="status-order-error">We couldn't submit this order. Please check your details and try again.</div>}<button type="submit" disabled={!detailsReady || !screenshot || createOrder.isPending} className="flex w-full items-center justify-center bg-primary py-4 text-[10px] font-bold uppercase tracking-[0.2em] text-primary-foreground transition hover:bg-accent disabled:cursor-not-allowed disabled:opacity-40" data-testid="button-submit-order">{createOrder.isPending ? 'Securing your order…' : 'Place private order'} <ArrowRight className="ml-2 h-4 w-4" /></button>
      </form><aside className="lg:sticky lg:top-28 lg:self-start"><div className="border border-border bg-card p-5 lg:p-7"><div className="mb-6 flex items-center justify-between"><h2 className="font-display text-2xl">Your selection</h2><span className="font-mono-brand text-[10px] text-muted-foreground">{cart.reduce((sum, item) => sum + item.quantity, 0)} pieces</span></div><div className="divide-y divide-border">{cart.map((item) => <div className="flex gap-3 py-4 first:pt-0" key={`${item.id}-${item.selectedSize}`} data-testid={`row-checkout-item-${item.id}`}><img src={productImage(item)} alt="" className="h-20 w-16 object-cover" /><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><p className="font-display text-sm">{item.name}</p><button onClick={() => onRemove(item.id, item.selectedSize)} className="text-muted-foreground hover:text-primary" data-testid={`button-remove-checkout-${item.id}`}><X className="h-3 w-3" /></button></div><p className="mt-1 font-mono-brand text-[9px] text-muted-foreground">Size {item.selectedSize}</p><div className="mt-3 flex items-center justify-between"><div className="flex items-center border border-border"><button type="button" className="p-1 text-muted-foreground hover:text-primary" onClick={() => onUpdate(item.id, item.selectedSize, -1)} data-testid={`button-checkout-decrease-${item.id}`}><Minus className="h-3 w-3" /></button><span className="w-6 text-center font-mono-brand text-[10px]">{item.quantity}</span><button type="button" className="p-1 text-muted-foreground hover:text-primary" onClick={() => onUpdate(item.id, item.selectedSize, 1)} data-testid={`button-checkout-increase-${item.id}`}><Plus className="h-3 w-3" /></button></div><span className="font-mono-brand text-[10px] text-primary">{formatCurrency(item.price * item.quantity)}</span></div></div></div>)}</div><div className="mt-4 flex justify-between border-t border-border pt-5"><span className="text-sm text-muted-foreground">Total</span><span className="font-mono-brand text-lg text-primary" data-testid="text-checkout-total">{formatCurrency(total)}</span></div></div><div className="mt-5 flex gap-3 text-[10px] leading-relaxed text-muted-foreground"><ShieldCheck className="h-4 w-4 shrink-0 text-primary" /> Your details are used only to fulfill this order. Delivery is arranged personally after payment verification.</div></aside></div></main>}
    </div>
  );
}
