import { ArrowUpRight, Instagram, Mail, MessageCircle, Phone, Music2 } from 'lucide-react';
import { Link } from 'wouter';

export default function Contact() {
  const links = [
    { label: 'Call the atelier', value: '+234 702 698 7674', href: 'tel:+2348000000000', icon: Phone },
    { label: 'WhatsApp concierge', value: '+234 912 397 6748', href: 'https://wa.me/2349123976748', icon: MessageCircle },
    { label: 'Email the house', value: 'hello@nobleluxe.com', href: 'mailto:nobleluxe18@gmail.com', icon: Mail },
    { label: 'TikTok', value: '@nobl.luxe', href: 'https://www.tiktok.com/@nobl.luxe', icon: Music2 },
  ];
  return <div className="min-h-screen bg-background"><header className="fixed inset-x-0 top-0 z-40 border-b border-border/70 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex h-[74px] max-w-[1440px] items-center justify-between px-5 lg:px-10"><Link href="/" className="font-display text-lg tracking-[.15em]">NOBLE LUXE</Link><Link href="/" className="text-[10px] uppercase tracking-[.18em] text-muted-foreground hover:text-primary">Return to showroom</Link></div></header><main className="mx-auto max-w-[1100px] px-5 pb-24 pt-36 lg:px-10"><p className="font-mono-brand text-[10px] uppercase tracking-[.22em] text-primary">The house is listening</p><h1 className="mt-4 max-w-3xl font-display text-6xl leading-[.94] lg:text-8xl">Speak to<br /><em className="text-primary">Noble Luxe.</em></h1><p className="mt-8 max-w-lg text-sm leading-8 text-muted-foreground">For styling, private appointments, delivery questions, or anything in between, our concierge team is here.</p><div className="mt-16 grid gap-px border border-border bg-border sm:grid-cols-2">{links.map(({ label, value, href, icon: Icon }) => <a key={label} href={href} target={href.startsWith('http') ? '_blank' : undefined} rel="noreferrer" className="group bg-card p-7 transition hover:bg-secondary"><Icon className="mb-12 h-5 w-5 text-primary" strokeWidth={1.3} /><p className="font-mono-brand text-[9px] uppercase tracking-[.18em] text-muted-foreground">{label}</p><div className="mt-3 flex items-center justify-between gap-4"><span className="font-display text-2xl">{value}</span><ArrowUpRight className="h-4 w-4 text-primary transition group-hover:translate-x-1 group-hover:-translate-y-1" /></div></a>)}</div></main></div>;
}